### PR TITLE
Command fixes

### LINKED ISSUE #133: Group assignment issues with filter applied
Groups are not assigned to the correct persons when command is used with a filter applied. 
e.g when filter is applied, and group "CS1231S" is applied to index 1 2 3 of the filtered list, the result is that the group "CS1231S" is assigned to 3 other persons. 

Possible pattern and issue observed: 
It seems that group is being assigned to the correct person for the first index, then for subsequent indexes it follows that of the original unfiltered list. e.g if index 1 2 3 is used, index 1 of the filtered list is assigned, then index 2 3 of the unfiltered list is assigned.

### LINKED ISSUE #134: Group unassignment issues with filter applied
Groups are not unassigned for the correct persons when command is used with a filter applied.
e.g when filter is applied, and group "CS1231S" is unassigned to index 1 2 3 of the filtered list, the result is that the group "CS1231S" is unassigned to 3 other persons.

Possible pattern and issue observed:
It seems that group is being unassigned for the correct person for the first index, then for subsequent indexes it follows that of the original unfiltered list. e.g if index 1 2 3 is used, index 1 of the filtered list is unassigned, then index 2 3 of the unfiltered list is unassigned.

### LINKED ISSUE #220: [PE-D][Tester C] No proper validation for phone number field when editing contact
Steps to reproduce
1) Launch the application
2) type `edit 1 p/+6591234567`
3) Observe the error message

Actual behaviour
Users can add any length of phone number and does not have the ability to add area codes +65. 

Expected behaviour
Currently, when user tries to edit a phone number field they are able to input more than 8 numbers. In Singapore, numbers are typically 8 numbers. 

If the app is intended for tutors to save numbers from different countries, it should allow area codes like +65 so that tutors are able to dfiferentiate the types of numbers. 

At the moment, there is also no limit for the amount of numbers users can key in. 

Suggestions
If the application is meant to be used in Singapore only, perhaps there can be some validation of phone numbers. Otherwise, it could be good to allow users to add area code 

Image

-------------
Labels: `severity.VeryLow` `type.FeatureFlaw`

### LINKED ISSUE #264: [PE-D][Tester C] List does not remain as filtered after group is assigned
Steps to reproduce
1) launch the application
2) For 3 contacts at index 1 , 2, 3 run this command `edit 1 t/jake` 
- change the number at the index field for the respective student accordingly
3) get the filtered list by running findtag t/jake
4) assign groups to these 3 contacts by running `group/assign 1 2 3 g/CS2040s`
5) Observe that after the assignment has been added the list reverts to the main full list 

Actual behaviour

Once the groups are assigned, the list no longer maintains the original filtered list. This issue is labelled as high severity as this bug makes it difficult for users to check if the groups have been correctly applied especially when the contacts book is large with over 100 contacts.  

Similar to #13, the groups are incorrectly correctly assigned. 

After running find 

Image

After assigning the groups 

Image

Expected behaviour 
Filter on the list should not be removed so users can verify that the correct groups have been assigned to the correct students

-------------
Labels: `severity.High` `type.FeatureFlaw`

### LINKED ISSUE #294: group/create allows multiple inputs
Command group/create should only allow 1 input as per the UG. Currently it allows multiple and only creates the last input. 

Suggestion:
Display warning and stop command from going through.

### PR DESCRIPTION
**Pull request by trekkie3**
Fixes many command bugs identified by our testers.

Fix #294 
Fix #264 
Fix #220 
Fix #134 
Fix #133

### CODE REVIEW

File: src/main/java/edutrack/model/person/Phone.java [hunk 1]
```diff
@@ -31,7 +32,8 @@ public static boolean isValidPhone(String test) {
         if (test == null || test.isEmpty()) {
             return true; // Allow null/empty for optional field
         }
-        return test.matches(VALIDATION_REGEX);
+        int digitCount = (int) test.chars().filter(Character::isDigit).count();
```
Comment (mengshuos) [inline src/main/java/edutrack/model/person/Phone.java]: Good use of filter and isDigit! I was worried that people might enter "+1      2" and it will be valid due to whitespaces counting as characters.

**Comment by mengshuos** [comment]
Looks good to me!
